#!/usr/bin/env python3
"""Generates addon/shadow_page.conf: the DX7 shadow-mode GUI for force-shadow.

Layout is computed here rather than hand-typed (7 tabs x ~25 widgets); rerun
after changing it. Keys/ranges come from src/dsp/dx7_plugin.cpp's own params.
Every tab carries the same BANK / PATCH steppers along the top.

  python3 scripts/gen_shadow_page.py            # rewrites addon/shadow_page.conf
"""
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "addon" / "shadow_page.conf"

HEADER = '''# force-dx7 shadow-mode page -- GENERATED by scripts/gen_shadow_page.py, edit that instead.
#
# Tabs: GLOBAL + OP1..OP6 (the six FM operators) + BANKS. The top bar of every tab
# has a bank readout (tap = BANKS) and a patch stepper (read back live). Style: DX7-editor LCD
# look (cyan on slate, dotted-arc knobs) -- deliberately unlike Maze Voice's
# cream-on-brown plate. int_values=1: dx7_host parses everything with atoi().
page=1
ctrl_sock=/tmp/dx7_ctrl.sock
display_name=DX7
style=lcd
int_values=1
theme_bg=0f1214
theme_panel=161a1d
theme_line=2f363b
theme_ink=d8dee2
theme_ink_dim=7c868c
theme_ink_faint=4b5359
theme_accent=4ad6d6
theme_accent_hi=9af2f2
theme_knob_face=0b0d0e
theme_knob_ring=2a3034
theme_bar=0a0c0d
theme_seg_active=4ad6d6
theme_seg_inactive=0b0d0e
theme_seg_active_tx=0a0c0d
theme_btn_text=0a0c0d
theme_well=0b0d0e
theme_knob_off=3a4247
theme_tab_on=12262a
theme_lcd=07100f
engine_process_name=dx7_host
engine_nsmodule_path=/media/662522/AddOns/ForceDX7/NSMODULE.json
engine_dirname=ForceDX7
engine_arguments_json=[{"NAME":"module-dir flag","VALUE":"--module-dir"},{"NAME":"module directory (module.json/banks source)","VALUE":"/media/662522/AddOns/ForceDX7"},{"NAME":"ctrl-sock flag","VALUE":"--ctrl-sock"},{"NAME":"control socket path","VALUE":"/tmp/dx7_ctrl.sock"},{"NAME":"control-channel flag","VALUE":"--control-channel"},{"NAME":"Q-Link control channel (1-16)","VALUE":"1"},{"NAME":"mix-slot flag","VALUE":"--mix-slot"},{"NAME":"ForceAudioJack voice slot (0-3; 2, since 0=Maze Voice, 1=JV-880)","VALUE":"2"}]
'''

BODY_Y = 88         # content starts right under the top bar
BODY_H = 636        # down to just above the tab bar
L, R = 36, 1244     # content left/right edges
BANKS_TAB = 7       # tab index of the BANKS page (the top-bar bank readout jumps here)

lines = []


def emit(s):
    lines.append(s)


def frame(x, y, w, h, title):
    emit(f'frame x={x} y={y} w={w} h={h} title="{title}"')


def knob(cx, cy, r, label, key, lo, hi, pct=50):
    emit(f'knob cx={cx} cy={cy} r={r} label="{label}" key={key} min={lo} max={hi} pct={pct}')


def toggle(cx, cy, label, key):
    emit(f'toggle cx={cx} cy={cy} label="{label}" key={key} on=0')


def enum_h(cx, cy, label, key, opts, sw):
    emit(f'enum_h cx={cx} cy={cy} label="{label}" key={key} options="{",".join(opts)}" active=0 sw={sw}')


def topbar():
    """Bank readout (tap = open BANKS) and patch stepper, in the top bar of every tab."""
    emit(f'readout cx=320 cy=36 w=300 h=48 label="" get=syx_bank_name clean=1 goto={BANKS_TAB}')
    emit('stepper cx=760 cy=36 w=520 h=48 label="" key=preset get=patch_name '
         'idx=preset count=preset_count min=0 max=31 numbered=1')


def row(n, x0, x1):
    """n evenly spaced centres between x0..x1."""
    step = (x1 - x0) / n
    return [round(x0 + step * (i + 0.5)) for i in range(n)]


def env_panel(x, y, w, h, title, prefix, name, graph_h, r, cy_r, cy_l):
    """Envelope graph on top, RATE 1-4 knobs stacked over LEVEL 1-4 knobs."""
    frame(x, y, w, h, title)
    emit(f'env cx={x + w // 2} cy={y + 44 + graph_h // 2 + 8} w={w - 48} h={graph_h} prefix={prefix}eg_'
         if prefix.startswith("op") else
         f'env cx={x + w // 2} cy={y + 44 + graph_h // 2 + 8} w={w - 48} h={graph_h} prefix={prefix}')
    xs = row(4, x, x + w)
    key_r = f"{prefix}eg_r" if prefix.startswith("op") else f"{prefix}r"
    key_l = f"{prefix}eg_l" if prefix.startswith("op") else f"{prefix}l"
    for i, cx in enumerate(xs):
        knob(cx, y + cy_r, r, f"RATE {i + 1}", f"{key_r}{i + 1}", 0, 99)
        knob(cx, y + cy_l, r, f"LEVEL {i + 1}", f"{key_l}{i + 1}", 0, 99)


def global_tab():
    emit('[tab GLOBAL]')
    topbar()
    h, gap = 210, 12
    y1 = BODY_Y
    y2 = y1 + h + gap
    h2 = BODY_Y + BODY_H - y2

    frame(L, y1, R - L, h, "VOICE")
    cy = y1 + 76
    xs = row(7, L, R)
    knob(xs[0], cy, 32, "ALGORITHM", "algorithm", 1, 32, 0)
    knob(xs[1], cy, 32, "FEEDBACK", "feedback", 0, 7, 0)
    knob(xs[2], cy, 32, "OUTPUT", "output_level", 0, 100)
    knob(xs[3], cy, 32, "OCTAVE", "octave_transpose", -3, 3)
    knob(xs[4], cy, 32, "TRANSPOSE", "transpose", 0, 48)
    toggle(xs[5], cy, "OSC SYNC", "osc_sync")
    knob(xs[6], cy, 32, "VOICE VOL", "mix.gain", 0, 150, 40)
    # Voice on/off removed here (redundant with the ENGINE power switch);
    # DEST replaces the old L/R/L+R channel notion with the destination
    # bus/channel a voice lands on (see forceAudioInject.h): I1, I2, I1+2
    # (stereo into Audio-In 1/2), O3, O4, O3+4 (stereo into Out 3/4) - I/O
    # prefix kept short (no "IN"/"OUT") so all 6 options still fit the
    # frame at a legible width; "+" not "," between paired numbers only
    # because enum_h's options list is itself comma-delimited - see web
    # GUI for the spelled-out "IN1,2"/"OUT3,4" labels.
    enum_h((L + R) // 2, y1 + 185, "DEST", "mix.dest_idx", ["I1", "I2", "O3", "O4", "I1+2", "O3+4"], 60)

    # LFO: half width, five knobs over the waveform selector + sync
    lw = 580
    frame(L, y2, lw, h2, "LFO")
    cy = y2 + 140
    for cx, (lbl, key, hi) in zip(row(5, L, L + lw),
                                  [("SPEED", "lfo_speed", 99), ("DELAY", "lfo_delay", 99),
                                   ("PMD", "lfo_pmd", 99), ("AMD", "lfo_amd", 99),
                                   ("PMS", "lfo_pms", 7)]):
        knob(cx, cy, 34, lbl, key, 0, hi)
    cy2 = y2 + 320
    enum_h(L + 20 + 209, cy2, "WAVEFORM", "lfo_wave", ["TRI", "SAWD", "SAWU", "SQR", "SIN", "S/H"], 68)
    toggle(L + lw - 68, cy2, "SYNC", "lfo_sync")

    # Pitch EG: graph with rate knobs stacked over level knobs, like the operators
    rx = L + lw + 16
    env_panel(rx, y2, R - rx, h2, "PITCH ENVELOPE", "pitch_eg_", "pitch", 104, 32, 214, 352)


def op_tab(n):
    p = f"op{n}_"
    emit(f'[tab OP{n}]')
    topbar()
    lw = 580
    rx = L + lw + 16
    rw = R - rx

    oh = 330
    frame(L, BODY_Y, lw, oh, f"OP{n} OSCILLATOR")
    c1 = BODY_Y + 96
    c2 = c1 + 140
    xs = row(4, L, L + lw)
    for cx, (lbl, key, hi) in zip(xs, [("LEVEL", "level", 99), ("COARSE", "coarse", 31),
                                       ("FINE", "fine", 99), ("DETUNE", "detune", 14)]):
        knob(cx, c1, 30, lbl, p + key, 0, hi)
    for cx, (lbl, key, hi) in zip(xs[:3], [("VEL SENS", "vel_sens", 7), ("AMP MOD", "amp_mod", 3),
                                           ("RATE SC", "rate_scale", 7)]):
        knob(cx, c2, 30, lbl, p + key, 0, hi)
    enum_h(xs[3] - 8, c2 + 4, "MODE", p + "osc_mode", ["RATIO", "FIXED"], 76)

    sy = BODY_Y + oh + 12
    frame(L, sy, lw, BODY_H - oh - 12, f"OP{n} KEY SCALING")
    k1 = sy + 96
    xs = row(3, L, L + lw)
    for cx, (lbl, key) in zip(xs, [("BREAKPT", "key_bp"), ("L DEPTH", "key_ld"), ("R DEPTH", "key_rd")]):
        knob(cx, k1, 30, lbl, p + key, 0, 99)
    e1 = sy + 232
    enum_h(L + 15 + 135, e1, "L CURVE", p + "key_lc", ["-LIN", "-EXP", "+EXP", "+LIN"], 66)
    enum_h(L + 15 + 270 + 10 + 135, e1, "R CURVE", p + "key_rc", ["-LIN", "-EXP", "+EXP", "+LIN"], 66)

    env_panel(rx, BODY_Y, rw, BODY_H, f"OP{n} ENVELOPE", p, "op", 210, 36, 330, 480)


def banks_tab():
    emit('[tab BANKS]')
    topbar()
    frame(L, BODY_Y, 724, BODY_H, "BANKS")
    emit(f'list x={L + 16} y={BODY_Y + 44} w=692 h=580 key=syx_bank_index items=syx_bank_list sel=syx_bank_index '
         'cols=2 rows=6 th=62 gap=10 jump=1 colmajor=0 numbered=0 scale=1.5')
    frame(776, BODY_Y, R - 776, BODY_H, "PATCHES")
    emit(f'list x=792 y={BODY_Y + 44} w=436 h=580 key=preset items=patch_list sel=preset '
         'cols=2 rows=16 th=33 gap=3 jump=0 colmajor=1 numbered=1 scale=1.5')


global_tab()
for n in range(1, 7):
    op_tab(n)
banks_tab()

OUT.write_text(HEADER + "\n" + "\n".join(lines) + "\n")
print(f"wrote {OUT} ({len(lines)} lines)")
