#!/usr/bin/env python3
"""Generates addon/shadow_page.conf: the DX7 shadow-mode GUI for force-shadow.

Layout is computed here rather than hand-typed (7 tabs x ~25 widgets); rerun
after changing it. Keys/ranges come from src/dsp/dx7_plugin.cpp's own params.
Every tab carries the same BANK / PATCH steppers along the top.

  python3 scripts/gen_shadow_page.py            # rewrites addon/shadow_page.conf
"""
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "addon" / "shadow_page.conf"

HEADER = '''# force-dx7 shadow-mode page -- GENERATED by scripts/gen_shadow_page.py, edit that instead.
#
# Tabs: GLOBAL + OP1..OP6 (the six FM operators). Every tab has BANK/PATCH
# steppers on top (read back live from the engine). Style: DX7-editor LCD
# look (cyan on slate, dotted-arc knobs) -- deliberately unlike Maze Voice's
# cream-on-brown plate. int_values=1: dx7_host parses everything with atoi().
page=1
ctrl_sock=/tmp/dx7_ctrl.sock
display_name=DX7
style=lcd
int_values=1
theme_bg=0f1214
theme_panel=161a1d
theme_line=2f363b
theme_ink=d8dee2
theme_ink_dim=7c868c
theme_ink_faint=4b5359
theme_accent=4ad6d6
theme_accent_hi=9af2f2
theme_knob_face=0b0d0e
theme_knob_ring=2a3034
theme_bar=0a0c0d
theme_seg_active=4ad6d6
theme_seg_inactive=0b0d0e
theme_seg_active_tx=0a0c0d
theme_btn_text=0a0c0d
theme_well=0b0d0e
theme_knob_off=3a4247
theme_tab_on=12262a
theme_lcd=07100f
engine_process_name=dx7_host
engine_nsmodule_path=/media/662522/AddOns/ForceDX7/NSMODULE.json
engine_dirname=ForceDX7
engine_arguments_json=[{"NAME":"module-dir flag","VALUE":"--module-dir"},{"NAME":"module directory (module.json/banks source)","VALUE":"/media/662522/AddOns/ForceDX7"},{"NAME":"ctrl-sock flag","VALUE":"--ctrl-sock"},{"NAME":"control socket path","VALUE":"/tmp/dx7_ctrl.sock"},{"NAME":"control-channel flag","VALUE":"--control-channel"},{"NAME":"Q-Link control channel (1-16)","VALUE":"1"},{"NAME":"mix-slot flag","VALUE":"--mix-slot"},{"NAME":"ForceAudioIn voice slot (0-3; 2, since 0=Maze Voice, 1=JV-880)","VALUE":"2"}]
'''

BODY_Y = 172        # below the BANK/PATCH strip
BODY_H = 552        # down to just above the tab bar
L, R = 36, 1244     # content left/right edges

lines = []


def emit(s):
    lines.append(s)


def frame(x, y, w, h, title):
    emit(f'frame x={x} y={y} w={w} h={h} title="{title}"')


def knob(cx, cy, r, label, key, lo, hi, pct=50):
    emit(f'knob cx={cx} cy={cy} r={r} label="{label}" key={key} min={lo} max={hi} pct={pct}')


def toggle(cx, cy, label, key):
    emit(f'toggle cx={cx} cy={cy} label="{label}" key={key} on=0')


def enum_h(cx, cy, label, key, opts, sw):
    emit(f'enum_h cx={cx} cy={cy} label="{label}" key={key} options="{",".join(opts)}" active=0 sw={sw}')


def strip():
    emit('stepper cx=296 cy=132 w=520 h=52 label="BANK" key=syx_bank_index get=syx_bank_name '
         'idx=syx_bank_index count=syx_bank_count min=0 max=0')
    emit('stepper cx=920 cy=132 w=648 h=52 label="PATCH" key=preset get=patch_name '
         'idx=preset count=preset_count min=0 max=31 numbered=1')


def row(n, x0, x1):
    """n evenly spaced centres between x0..x1."""
    step = (x1 - x0) / n
    return [round(x0 + step * (i + 0.5)) for i in range(n)]


def global_tab():
    emit('[tab GLOBAL]')
    strip()
    h, gap = 172, 10
    y1, y2, y3 = BODY_Y, BODY_Y + h + gap, BODY_Y + 2 * (h + gap)

    frame(L, y1, R - L, h, "VOICE")
    cy = y1 + 90
    xs = row(8, L, R)
    knob(xs[0], cy, 30, "ALGORITHM", "algorithm", 1, 32, 0)
    knob(xs[1], cy, 30, "FEEDBACK", "feedback", 0, 7, 0)
    knob(xs[2], cy, 30, "OUTPUT", "output_level", 0, 100)
    knob(xs[3], cy, 30, "OCTAVE", "octave_transpose", -3, 3)
    knob(xs[4], cy, 30, "TRANSPOSE", "transpose", 0, 48)
    toggle(xs[5], cy, "OSC SYNC", "osc_sync")
    knob(xs[6], cy, 30, "VOICE VOL", "mix.gain", 0, 150, 40)
    toggle(xs[7], cy, "VOICE OUT", "mix.enabled")

    frame(L, y2, R - L, h, "LFO")
    cy = y2 + 90
    for cx, (lbl, key, hi) in zip([90, 210, 330, 450, 570],
                                  [("SPEED", "lfo_speed", 99), ("DELAY", "lfo_delay", 99),
                                   ("PMD", "lfo_pmd", 99), ("AMD", "lfo_amd", 99),
                                   ("PMS", "lfo_pms", 7)]):
        knob(cx, cy, 30, lbl, key, 0, hi)
    enum_h(900, y2 + 100, "WAVEFORM", "lfo_wave", ["TRI", "SAWD", "SAWU", "SQR", "SIN", "S/H"], 68)
    toggle(1180, cy, "SYNC", "lfo_sync")

    frame(L, y3, R - L, h, "PITCH ENVELOPE")
    cy = y3 + 90
    xs = row(8, L, R)
    for i in range(4):
        knob(xs[i], cy, 30, f"RATE {i + 1}", f"pitch_eg_r{i + 1}", 0, 99)
    for i in range(4):
        knob(xs[4 + i], cy, 30, f"LEVEL {i + 1}", f"pitch_eg_l{i + 1}", 0, 99)


def op_tab(n):
    p = f"op{n}_"
    emit(f'[tab OP{n}]')
    strip()
    lw = 580
    rx = L + lw + 16
    rw = R - rx

    # oscillator
    oh = 287
    frame(L, BODY_Y, lw, oh, f"OP{n} OSCILLATOR")
    c1 = BODY_Y + 86
    c2 = c1 + 118
    xs = row(4, L, L + lw)
    for cx, (lbl, key, hi) in zip(xs, [("LEVEL", "level", 99), ("COARSE", "coarse", 31),
                                       ("FINE", "fine", 99), ("DETUNE", "detune", 14)]):
        knob(cx, c1, 26, lbl, p + key, 0, hi)
    for cx, (lbl, key, hi) in zip(xs[:3], [("VEL SENS", "vel_sens", 7), ("AMP MOD", "amp_mod", 3),
                                           ("RATE SC", "rate_scale", 7)]):
        knob(cx, c2, 26, lbl, p + key, 0, hi)
    enum_h(xs[3] - 8, c2 + 4, "MODE", p + "osc_mode", ["RATIO", "FIXED"], 76)

    # key scaling
    sy = BODY_Y + oh + 12
    frame(L, sy, lw, BODY_H - oh - 12, f"OP{n} KEY SCALING")
    k1 = sy + 86
    xs = row(3, L, L + lw)
    for cx, (lbl, key) in zip(xs, [("BREAKPT", "key_bp"), ("L DEPTH", "key_ld"), ("R DEPTH", "key_rd")]):
        knob(cx, k1, 26, lbl, p + key, 0, 99)
    e1 = k1 + 126
    enum_h(L + 15 + 135, e1, "L CURVE", p + "key_lc", ["-LIN", "-EXP", "+EXP", "+LIN"], 66)
    enum_h(L + 15 + 270 + 10 + 135, e1, "R CURVE", p + "key_rc", ["-LIN", "-EXP", "+EXP", "+LIN"], 66)

    # envelope
    frame(rx, BODY_Y, rw, BODY_H, f"OP{n} ENVELOPE")
    emit(f'env cx={rx + rw // 2} cy={BODY_Y + 130} w={rw - 48} h=170 prefix={p}eg_')
    xs = row(4, rx, rx + rw)
    r1 = BODY_Y + 282
    for i, cx in enumerate(xs):
        knob(cx, r1, 34, f"RATE {i + 1}", f"{p}eg_r{i + 1}", 0, 99)
        knob(cx, r1 + 134, 34, f"LEVEL {i + 1}", f"{p}eg_l{i + 1}", 0, 99)


global_tab()
for n in range(1, 7):
    op_tab(n)

OUT.write_text(HEADER + "\n" + "\n".join(lines) + "\n")
print(f"wrote {OUT} ({len(lines)} lines)")
